-- 1. Create missing Health tables
CREATE TABLE IF NOT EXISTS public.saglik_moods (
    id TEXT PRIMARY KEY,
    "user" TEXT NOT NULL,
    mood JSONB NOT NULL,
    note TEXT,
    kategori TEXT DEFAULT 'Genel',
    date TIMESTAMPTZ DEFAULT NOW(),
    family_id TEXT DEFAULT 'ERAYLAR'
);

CREATE TABLE IF NOT EXISTS public.saglik_logs (
    id TEXT PRIMARY KEY,
    med_id TEXT NOT NULL,
    ad TEXT NOT NULL,
    kisi TEXT NOT NULL,
    slot TEXT NOT NULL,
    date TEXT NOT NULL,
    dt TEXT NOT NULL,
    family_id TEXT DEFAULT 'ERAYLAR'
);

-- 2. Disable RLS for ALL relevant tables (Ensures mobile/anon writes work)
ALTER TABLE IF EXISTS public.saglik_moods DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.saglik_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.finans_kartlar DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.finans_krediler DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.finans_onay_havuzu DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.hedefler_aktif DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.hedefler_gecmis DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.hedefler_vizyon DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.mutfak_stok DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.mutfak_tarifler DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.mutfak_menu DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.mutfak_su DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.alisveris_listesi DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sosyal_etkinlikler DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sosyal_havuz DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sosyal_rutinler DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ev_duzenli_odemeler DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ev_abonelikler DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ev_onarim DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ev_demirbaslar DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ev_bakimlar DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.garaj_yakit DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.garaj_servis DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.garaj_belgeler DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pet_asilar DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pet_agirlik DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.saglik_randevular DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.saglik_ilaclar DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.saglik_olcumler DISABLE ROW LEVEL SECURITY;

-- 3. Grant full access (just in case)
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
